### ISSUE TITLE
Radikoの録音ができない

### ISSUE THREAD

**Issue by tnira** [yayugu/net-radio-archive#64]
12月２日の20時頃から、Radikoの録音ができない状態になっているようなので Issue上げさせていただきます。

直近のproductoin.logの一部を掲載します。
```
E, [2020-12-05T09:25:06.723916 #32684] ERROR -- : [
"
NoMethodError#<NoMethodError: undefined method `[]' for nil:NilClass>
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:99:in `block in auth1'
/usr/lib/ruby/2.5.0/net/http.rb:910:in `start'
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:86:in `auth1'
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:42:in `auth'
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:30:in `block in exec_rec'
/home/ubuntu/net-radio-archive/lib/main.rb:10:in `block in retry'
/home/ubuntu/net-radio-archive/lib/main.rb:8:in `times'
/home/ubuntu/net-radio-archive/lib/main.rb:8:in `retry'
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:29:in `exec_rec'
/home/ubuntu/net-radio-archive/lib/radiko/recording.rb:17:in `record'
/home/ubuntu/net-radio-archive/lib/main/main.rb:226:in `block in rec_one'
/home/ubuntu/net-radio-archive/lib/main/main.rb:310:in `block (2 levels) in threads_from_records'
"
]
```

**Comment by tnira** [comment]
#66 #68 にて配信している放送局全てで録音できることを確認しました。
対応してくださった方々、ありがとうございました。
